/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pertemuan10;

import static pertemuan10.dbKoneksi.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Rambu Intan
 */
public class fMahasiswa extends javax.swing.JFrame {
    DefaultTableModel DTM = new DefaultTableModel();
    

    /**
     * Creates new form fMahasiswa
     */
    public fMahasiswa() throws SQLException {
        initComponents();
        
        tblmhs.setModel(DTM);
        DTM.addColumn("Nim");
        DTM.addColumn("Nama Mahasiswa");
        DTM.addColumn("Jurusan");
        DTM.addColumn("Alamat");
        
        String[] opsiJUR = {"Pilih Jurusan","KAB","MTI","DKV","TIPAR","BD","RSK"};
        cbJUR.removeAllItems();
        for(int i=0;i<7;i++){
            cbJUR.addItem(opsiJUR[i]);
        }
        
        lsdtmhs();
        clearform();
        
        

        }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txNim = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txNama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txJur = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txAlamat = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblmhs = new javax.swing.JTable();
        cBaru = new javax.swing.JButton();
        cHapus = new javax.swing.JButton();
        cUbah = new javax.swing.JButton();
        cTutup = new javax.swing.JButton();
        cbJUR = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 200));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Data Mahasiswa");

        jLabel2.setText("Nim");

        jLabel3.setText("Nama Mahasiswa");

        txNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNamaActionPerformed(evt);
            }
        });

        jLabel4.setText("Jurusan");

        txJur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txJurActionPerformed(evt);
            }
        });

        jLabel5.setText("Alamat");

        tblmhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblmhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblmhsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblmhs);

        cBaru.setText("Baru");
        cBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBaruActionPerformed(evt);
            }
        });

        cHapus.setText("Hapus");
        cHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cHapusActionPerformed(evt);
            }
        });

        cUbah.setText("Ubah");
        cUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cUbahActionPerformed(evt);
            }
        });

        cTutup.setText("Tutup");
        cTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTutupActionPerformed(evt);
            }
        });

        cbJUR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(txNama, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cBaru)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cUbah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cTutup)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)
                        .addGap(175, 175, 175)
                        .addComponent(jLabel3))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txNim, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(164, 164, 164)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txJur, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(txAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbJUR, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(360, 360, 360))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBaru)
                    .addComponent(cHapus)
                    .addComponent(cUbah)
                    .addComponent(cTutup)
                    .addComponent(txNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txJur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(cbJUR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNamaActionPerformed

    private void txJurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txJurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txJurActionPerformed

    private void cHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cHapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cHapusActionPerformed

    private void cTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTutupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cTutupActionPerformed

    private void tblmhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblmhsMouseClicked
        txNim.setText(tblmhs.getValueAt(tblmhs.getSelectedRow() , 0).toString());
        txNama.setText(tblmhs.getValueAt(tblmhs.getSelectedRow() , 1).toString());
        txJur.setText(tblmhs.getValueAt(tblmhs.getSelectedRow() , 2).toString());
        txAlamat.setText(tblmhs.getValueAt(tblmhs.getSelectedRow() , 3).toString());
        
    }//GEN-LAST:event_tblmhsMouseClicked

    private void cBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBaruActionPerformed

        if(cBaru.getText().equals("Baru")){
        clearform();
        cBaru.setText("Simpan");
        cTutup.setEnabled(false);
        cUbah.setEnabled(false);
        cHapus.setEnabled(false);
    }else{
        StoreData();
        lsdtmhs();
        cBaru.setText("Baru");
        cTutup.setEnabled(false);
        cUbah.setEnabled(false);
        cHapus.setEnabled(false);
    }//GEN-LAST:event_cBaruActionPerformed
    }
    private void cUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cUbahActionPerformed
         if(cUbah.getText().equals("Ubah")){
        clearform();
        cUbah.setText("Simpan");
    }else{
        cUbah.setText("Ubah");
        
    }                 
                                  
    }//GEN-LAST:event_cUbahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new fMahasiswa().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(fMahasiswa.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cBaru;
    private javax.swing.JButton cHapus;
    private javax.swing.JButton cTutup;
    private javax.swing.JButton cUbah;
    private javax.swing.JComboBox<String> cbJUR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblmhs;
    private javax.swing.JTextField txAlamat;
    private javax.swing.JTextField txJur;
    private javax.swing.JTextField txNama;
    private javax.swing.JTextField txNim;
    // End of variables declaration//GEN-END:variables

    private void lsdtmhs() throws SQLException {
        Connection cnn = koneksi();
        
        DTM.getDataVector().removeAllElements();
        DTM.fireTableDataChanged();
        
        
       if(!cnn.isClosed()){
           PreparedStatement PS = cnn.prepareCall("SElECT * FROM mhs;");
           ResultSet RS = PS.executeQuery();
           while( RS.next()){
               Object[] dtmhs = new Object [4];
                  dtmhs[0] = RS.getString("NIM");
                  dtmhs[1] = RS.getString("NAMA");
                  dtmhs[2] = RS.getString("JURUSAN");
                  dtmhs[3] = RS.getString("ALAMAT");
                  
                  DTM.addRow(dtmhs);
               
               
               
               
           }
         
       }
    }
    
    private void clearform(){
        txNama.setText("");
        txNim.setText("");
        txJur.setText("");
        txAlamat.setText("");
    }

    private void StoreData() throws SQLException {
        Connection cnn = koneksi();
        String nim = txNim.getText();
        String nama = txNama.getText();
        String jur = txJur.getText();
        String alamat = txAlamat.getText();
        
       if(cnn.isClosed()){
           PreparedStatement PS = cnn.prepareStatement("INSERT, INTO mhs(NIM,NAMA,JURUSAN,ALAMAT)VALUES(?,?,?,?);");
           PS.setString(1, nim);
           PS.setString(2, nama);
           PS.setString(3, jur);
           PS.setString(4, alamat);
           PS.executeUpdate();
           cnn.close();
       }
   
    }
}
